name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Packages
        run: bun i

      - name: Run TypeScript Compiler
        run: bun run tsc

      - name: Run ESLint
        run: bun run lint
    permissions:
      contents: read
      pull-requests: read
      checks: write
